cmake_minimum_required (VERSION 3.25)
set(PACKAGE_NAMESPACE demo)
set(PACKAGE_NAME traa)
project(${PACKAGE_NAME})
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
list(
    APPEND
    CMAKE_MODULE_PATH
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
include(cmake_utils)


option(USE_TEST "use tests" ON)


set(
    PROJECT_DEPS
    # PKG <package_name>
)
find_pkgs(PROJECT_DEPS)
if(USE_TEST)
    enable_testing()
    find_package(GTest REQUIRED)
endif()



handle_version()
add_subdirectory(traaxx)
add_subdirectory(traapp)



if(USE_TEST)
    add_subdirectory(tests)
endif()


install_package_config()


if(CMAKE_EXPORT_COMPILE_COMMANDS)
    file(
        CREATE_LINK
        "${CMAKE_BINARY_DIR}/compile_commands.json"
        "${CMAKE_SOURCE_DIR}/compile_commands.json"
        SYMBOLIC)
endif()
