FROM ubuntu:26.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN  apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    ninja-build \
    ca-certificates \
    libgtest-dev \
    libgmock-dev \
    clang \
    clangd \
    clang-tidy \
    clang-format \
    git \
    sudo

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN if getent passwd $USER_UID > /dev/null; then userdel -r "$(getent passwd $USER_UID | cut -d: -f1)"; fi \
    && if getent group $USER_GID > /dev/null; then groupdel "$(getent group $USER_GID | cut -d: -f1)"; fi \
    && groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo "$USERNAME ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME
