function(give_dirs)
    set(options NO_RECURSE)
    set(oneValueArgs VAR)
    set(multiValueArgs DIRS)
    cmake_parse_arguments(
        PARAM "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    set(_my_dirs_list "")
    foreach(_dd IN LISTS PARAM_DIRS)
        unset(_temp)
        if(PARAM_NO_RECURSE)
            file(GLOB _temp LIST_DIRECTORIES true "${_dd}/*")
        else()
            file(GLOB_RECURSE _temp LIST_DIRECTORIES true "${_dd}")
        endif()
        foreach(_it IN LISTS _temp)
            if(IS_DIRECTORY "${_it}")
                list(APPEND _my_dirs_list "${_it}")
            endif()
        endforeach()
    endforeach()
    set(${PARAM_VAR} ${_my_dirs_list} PARENT_SCOPE)
endfunction()
