function(give_files)
    set(options NO_RECURSE)
    set(oneValueArgs VAR)
    set(multiValueArgs DIRS FILTERS)
    cmake_parse_arguments(
        VGF "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    set(_my_files "")
    foreach(_it IN LISTS VGF_FILTERS)
        foreach(_dd IN LISTS VGF_DIRS)
            if(NOT VGF_NO_RECURSE)
                file(GLOB_RECURSE _temp ${_dd}/${_it})
            else()
                file(GLOB _temp ${_dd}/${_it})
            endif()
            list(APPEND _my_files ${_temp})
        endforeach()
    endforeach()
    set(${VGF_VAR} ${_my_files} PARENT_SCOPE)
endfunction()
